[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
allow = ["Apache-2.0", "BSD-2-Clause", "BSD-3-Clause", "ISC", "MIT"]
deny = []
copyleft = "deny"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8
exceptions = [
    { allow = [
        "ISC",
        "MIT",
        "OpenSSL",
    ], name = "ring", version = "*" },

    # The Unicode-DFS--2016 license is necessary for unicode-ident because they
    # use data from the unicode tables to generate the tables which are
    # included in the application. We do not distribute those data files so
    # this is not a problem for us. See https://github.com/dtolnay/unicode-ident/pull/9/files
    # for more details.
    { allow = [
        "MIT",
        "Apache-2.0",
        "Unicode-DFS-2016",
    ], name = "unicode-ident" },
    { allow = ["Zlib"], name = "adler32" },
]

[[licenses.clarify]]
name = "ring"
version = "*"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[bans]
multiple-versions = "deny"
wildcards = "allow"
highlight = "all"
deny = []
skip = [
    # `rustls-pemfile` and `k8s-openapi` depend on versions of `base64` that
    # have diverged significantly.
    { name = "base64" },
    # `num_cpus` (transitive dep of `metrics-util` and `tokio`) and
    # `io-lifetimes` (a transitive dep of `metrics-process`) depend on
    # incompatible versions of this crate.
    { name = "hermit-abi" },
]
skip-tree = [
    { name = "windows-sys" },
    { name = "windows_aarch64_msvc" },
    { name = "windows_i686_gnu" },
    { name = "windows_i686_msvc" },
    { name = "windows_x86_64_gnu" },
    { name = "windows_x86_64_msvc" },
    # `metrics` and `kube-runtime` have conflicting versions of `ahash` and
    # `wasi`.
    # TODO(eliza): remove this skip when the conflicts are resolved.
    { name = "metrics" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
